version: 0.1.{build}

shallow_clone: true

image: Visual Studio 2017

environment:
  appveyor_api_key:
    secure:
      JCVa4YmZI+ct0f0LSYPOBFzK1rw/UM2xEgka3UgvXhI=
  makefile_location: "."
  makefile_name: makefile.libretro
  target_name: fceumm

configuration:
  - release

platform:
  - windows_msvc2017_uwp_x64
  - windows_msvc2017_uwp_x86
  - windows_msvc2017_uwp_arm
  - windows_msvc2017_desktop_x64
  - windows_msvc2017_desktop_x86
  - nuget

init:
  - set Path=C:\msys64\usr\bin;%Path%

build_script:
  -cmd: |
      echo mgoiweoso;p;g;
      IF %PLATFORM% NEQ "nuget" (
        cd %makefile_location%
        make -f %makefile_name% platform=%platform%
      )

artifacts:
  - path: '**\%target_name%*.dll'
  - path: '**\%target_name%*.lib'
  - path: '**\%target_name%*.pdb'
  - path: '**\libretro.h'
  - path: '**\*.nupkg'
